name: Deploy to GitHub Pages

on:
    workflow_dispatch:
#   workflow_run: # Trigger on completion of another workflow
#     workflows: ["Download File Periodically"]
#     types:
#       - completed

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4